spring:
  application:
    name: antlia
  profiles:
    active: localhost

---
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: jdbc:sqlserver://VMEXAME15\\SQLEXPRESS:1433;databaseName=MovimentosManuais;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: candidato123
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect